### ISSUE TITLE
documentation url on how to use it is not working

### ISSUE THREAD

**Issue by odion-cloud** [laravel-enso/charts#12]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by aocneanu** [comment]
What do you mean?

[link from the readme page](https://docs.laravel-enso.com/backend/charts.html)

[also front-end](https://docs.laravel-enso.com/frontend/charts.html)
