### ISSUE TITLE
¿Money values in dataset?

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/charts#7]
This is  a **feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Good morning, I would like to make a linear chart of the sales of the month. At the moment I have no problem doing it, just that I would like the values to be shown in money format, it would give a better appearance to my chart. I have tried in many ways without being able to get it :(
Do you think there is a way to achieve it?.

**Comment by aocneanu** [comment]
`Chart.vue` has a `formatter` prop where you can pass a function to achieve exactly that.

The formatter is for the `datalabels` [plugin](https://chartjs-plugin-datalabels.netlify.com/guide/formatting.html#formatting) (already used in the component)

**Comment by aocneanu** [comment]
And, you can search for `numberFormat` or `shortNumber` in `enso-ui/ui` and find maybe useful examples.

**Comment by aocneanu** [comment]
@heyner29 can we close this?

**Comment by heyner29** [comment]
Yes, excuse me.  I solved it as you suggested, once again a thousand thanks.
